version: '3.9'

services:
  django:
    build: ./server
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - fastapi
    env_file:
      - ./server/.env  # optional, if you have one

  fastapi:
    build: ./model
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    volumes:
      - ./model:/app
    env_file:
      - ./model/.env  # optional
